#!/usr/bin/env python3
"""Generate a flat list of every (dataset, style, judge, rewriter) run.

Sibling of gen_rerun_flat.py, but emits the FULL cross product instead of
filtering against rl_tables_base.tex. Already-executed combos still appear;
run_grid.sh skips them at runtime via its prior-log check.

Defaults mirror run_grid.sh's *_DEFAULT arrays; override on the command line.
"""

from __future__ import annotations

import argparse
from pathlib import Path

DATASETS = [
    "dataset/dprk_fraud_llm.json",
    "dataset/promptsteal_llm.json",
    "dataset/quietvault_llm.json",
]
STYLES = [
    "command_form", "compliance_audit", "direct",
    "educational", "helpdesk", "sysadmin",
]
JUDGES = [
    "meta-llama/llama-guard-4-12b",
    "anthropic/claude-sonnet-4-6",
    "anthropic/claude-opus-4-6",
    "openai/gpt-5.4-mini-2026-03-17",
]
REWRITERS = [
    "anthropic/claude-sonnet-4-6",
    "anthropic/claude-opus-4-6",
    "openai/gpt-5.4-mini-2026-03-17",
    "openai/gpt-5.4",
    "deepseek/deepseek-v4-flash",
]


def split_csv(s: str | None, default: list[str]) -> list[str]:
    if not s:
        return default
    return [x.strip() for x in s.split(",") if x.strip()]


def main():
    here = Path(__file__).resolve().parent
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--datasets", default=None, help="csv of dataset paths")
    ap.add_argument("--styles", default=None, help="csv of variation styles")
    ap.add_argument("--judges", default=None, help="csv of judge model ids")
    ap.add_argument("--rewriters", default=None, help="csv of rewriter model ids")
    ap.add_argument("--out", type=Path, default=here / "run_all_flat.sh")
    args = ap.parse_args()

    datasets = split_csv(args.datasets, DATASETS)
    styles = split_csv(args.styles, STYLES)
    judges = split_csv(args.judges, JUDGES)
    rewriters = split_csv(args.rewriters, REWRITERS)

    rows = [
        (ds, st, j, r)
        for ds in datasets for st in styles for j in judges for r in rewriters
    ]

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "set -a; source .env; set +a",
        "",
        "# Auto-generated by gen_run_all_flat.py.",
        "# Full cross product of (dataset, style, judge, rewriter).",
        f"# {len(datasets)} datasets x {len(styles)} styles x "
        f"{len(judges)} judges x {len(rewriters)} rewriters = {len(rows)} runs.",
        "# run_grid.sh skips combos whose log already shows a clean prior run.",
        "",
    ]
    for ds, st, j, r in rows:
        lines.append(
            f"bash ./run_grid.sh --datasets={ds} --styles={st} "
            f"--judges={j} --rewriters={r}"
        )
    args.out.write_text("\n".join(lines) + "\n")
    args.out.chmod(0o755)
    print(f"wrote {args.out} ({len(rows)} runs)")


if __name__ == "__main__":
    main()
