#!/usr/bin/env bash
set -euo pipefail
set -a; source .env; set +a

# Auto-generated from rl_tables_base.tex by gen_rerun_flat.py.
# Includes cells that are --- (never run) AND cells with (0.0) / (+0.0) delta.
# Total cases: 266

bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=meta-llama/llama-guard-4-12b --styles=command_form --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=meta-llama/llama-guard-4-12b --styles=command_form --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=command_form --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=command_form --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-opus-4-6 --styles=command_form --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-opus-4-6 --styles=command_form --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-opus-4-6 --styles=command_form --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=command_form --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=command_form --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=command_form --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=command_form --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=command_form --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=meta-llama/llama-guard-4-12b --styles=compliance_audit --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=meta-llama/llama-guard-4-12b --styles=compliance_audit --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=compliance_audit --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=compliance_audit --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-opus-4-6 --styles=compliance_audit --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-opus-4-6 --styles=compliance_audit --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=compliance_audit --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=compliance_audit --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=compliance_audit --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=compliance_audit --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=compliance_audit --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=meta-llama/llama-guard-4-12b --styles=direct --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=meta-llama/llama-guard-4-12b --styles=direct --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=direct --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=direct --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=direct --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-opus-4-6 --styles=direct --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-opus-4-6 --styles=direct --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=direct --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=direct --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=direct --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=direct --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=direct --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=meta-llama/llama-guard-4-12b --styles=educational --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=meta-llama/llama-guard-4-12b --styles=educational --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=educational --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=educational --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=educational --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=educational --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=educational --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-opus-4-6 --styles=educational --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-opus-4-6 --styles=educational --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-opus-4-6 --styles=educational --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-opus-4-6 --styles=educational --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-opus-4-6 --styles=educational --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=educational --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=educational --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=educational --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=educational --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=educational --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=meta-llama/llama-guard-4-12b --styles=helpdesk --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=meta-llama/llama-guard-4-12b --styles=helpdesk --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=helpdesk --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=helpdesk --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-opus-4-6 --styles=helpdesk --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-opus-4-6 --styles=helpdesk --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-opus-4-6 --styles=helpdesk --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-opus-4-6 --styles=helpdesk --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-opus-4-6 --styles=helpdesk --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=helpdesk --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=helpdesk --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=helpdesk --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=helpdesk --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=helpdesk --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=meta-llama/llama-guard-4-12b --styles=sysadmin --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=meta-llama/llama-guard-4-12b --styles=sysadmin --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=sysadmin --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=sysadmin --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=sysadmin --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-opus-4-6 --styles=sysadmin --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=anthropic/claude-opus-4-6 --styles=sysadmin --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=sysadmin --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=sysadmin --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=sysadmin --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=sysadmin --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/dprk_fraud_llm.json --judges=openai/gpt-5.4-mini --styles=sysadmin --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=meta-llama/llama-guard-4-12b --styles=command_form --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=meta-llama/llama-guard-4-12b --styles=command_form --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=command_form --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=command_form --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=command_form --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=command_form --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=command_form --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=command_form --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=command_form --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=command_form --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=command_form --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=command_form --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=meta-llama/llama-guard-4-12b --styles=compliance_audit --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=meta-llama/llama-guard-4-12b --styles=compliance_audit --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=compliance_audit --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=compliance_audit --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=compliance_audit --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=compliance_audit --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=compliance_audit --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=compliance_audit --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=compliance_audit --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=compliance_audit --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=compliance_audit --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=compliance_audit --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=compliance_audit --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=compliance_audit --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=compliance_audit --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=meta-llama/llama-guard-4-12b --styles=direct --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=meta-llama/llama-guard-4-12b --styles=direct --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=direct --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=direct --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=direct --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=direct --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=direct --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=direct --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=direct --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=direct --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=direct --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=direct --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=direct --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=direct --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=meta-llama/llama-guard-4-12b --styles=educational --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=meta-llama/llama-guard-4-12b --styles=educational --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=meta-llama/llama-guard-4-12b --styles=educational --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=meta-llama/llama-guard-4-12b --styles=educational --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=educational --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=educational --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=educational --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=educational --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=educational --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=educational --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=educational --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=educational --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=educational --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=educational --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=meta-llama/llama-guard-4-12b --styles=helpdesk --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=meta-llama/llama-guard-4-12b --styles=helpdesk --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=helpdesk --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=helpdesk --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=helpdesk --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=helpdesk --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=helpdesk --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=helpdesk --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=helpdesk --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=helpdesk --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=helpdesk --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=helpdesk --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=helpdesk --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=helpdesk --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=helpdesk --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=helpdesk --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=helpdesk --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=meta-llama/llama-guard-4-12b --styles=sysadmin --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=meta-llama/llama-guard-4-12b --styles=sysadmin --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=sysadmin --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=sysadmin --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=sysadmin --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=sysadmin --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=sysadmin --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=sysadmin --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=sysadmin --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=sysadmin --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=sysadmin --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=anthropic/claude-opus-4-6 --styles=sysadmin --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=sysadmin --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=sysadmin --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=sysadmin --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=sysadmin --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/promptsteal_llm.json --judges=openai/gpt-5.4-mini --styles=sysadmin --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=command_form --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=command_form --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=command_form --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=command_form --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=command_form --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=command_form --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=command_form --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=command_form --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=command_form --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=command_form --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=command_form --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=command_form --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=command_form --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=command_form --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=compliance_audit --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=compliance_audit --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=compliance_audit --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=compliance_audit --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=compliance_audit --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=compliance_audit --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=compliance_audit --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=compliance_audit --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=compliance_audit --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=compliance_audit --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=compliance_audit --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=compliance_audit --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=compliance_audit --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=compliance_audit --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=compliance_audit --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=direct --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=direct --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=direct --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=direct --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=direct --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=direct --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=direct --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=direct --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=direct --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=direct --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=direct --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=direct --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=direct --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=direct --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=direct --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=direct --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=direct --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=direct --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=educational --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=educational --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=educational --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=educational --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=educational --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=educational --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=educational --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=educational --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=educational --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=educational --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=educational --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=educational --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=educational --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=educational --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=educational --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=educational --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=educational --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=educational --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=educational --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=helpdesk --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=helpdesk --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=helpdesk --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=helpdesk --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=helpdesk --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=helpdesk --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=helpdesk --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=helpdesk --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=helpdesk --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=helpdesk --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=helpdesk --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=helpdesk --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=helpdesk --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=helpdesk --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=helpdesk --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=helpdesk --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=helpdesk --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=sysadmin --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=sysadmin --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=sysadmin --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=sysadmin --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=meta-llama/llama-guard-4-12b --styles=sysadmin --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=sysadmin --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=sysadmin --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=sysadmin --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-sonnet-4-6 --styles=sysadmin --rewriters=deepseek/deepseek-v4-flash
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=sysadmin --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=anthropic/claude-opus-4-6 --styles=sysadmin --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=sysadmin --rewriters=anthropic/claude-sonnet-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=sysadmin --rewriters=anthropic/claude-opus-4-6
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=sysadmin --rewriters=openai/gpt-5.4-mini-2026-03-17
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=sysadmin --rewriters=azure/gpt-5.4
bash ./run_grid.sh --datasets=dataset/quietvault_llm.json --judges=openai/gpt-5.4-mini --styles=sysadmin --rewriters=deepseek/deepseek-v4-flash
